

configProfile=develop
#server.port: 443
server.ssl.key-store: /opt/CA/_.in.nonprod.jks
server.ssl.key-store-password: hirRPP060eAGFCtsq6Qc
server.ssl.keyStoreType: JKS


##bootstrap.servers=cpkafka01-in00c1.in.infra:9092,cpkafka02-in00c1.in.infra:9092,cpkafka03-in00c1.in.infra:9092
#spring.kafka.template.default-topic=fake.contacts.loxon.data
spring.kafka.template.default-topic=lcs.core.task-import.v1

spring.kafka.consumer.group-id=kafka-test-app
spring.kafka.consumer.bootstrap-servers=cpkafka01-in00c1.in.infra:9092,cpkafka02-in00c1.in.infra:9092,cpkafka03-in00c1.in.infra:9092
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="FAKECONTACTS_User" password="FAKECONTACTS_User";
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-256
basic.auth.credentials.source=USER_INFO
basic.auth.user.info=FAKECONTACTS_User:FAKECONTACTS_User
schema.registry.url=https://schema-registry-in00c1.in.infra:8081

producer.kafka.topic.enable.idempotence=false
producer.kafka.topic.timeout.ms=30000



